### ISSUE TITLE
Core to log matching

### ISSUE THREAD

**Issue by atwahsz** [gazprom-neft/petroflow#34]
Hello I’m trying to do this but I’m having a hard time

I have 100 well and 100 cores

Well has 100 las file containing depth neutron porosity log
And I have 100 cores csv with depth and helium porosity measurement 

How can I match and generate new depth for the cores

**Comment by alexandrkuvaev** [comment]
Hi!

First, you need to convert your data to `PetroFlow` format, as described [here](https://github.com/gazprom-neft/petroflow/blob/master/well_format.md). Note, that the matching procedure requires not only a pair of well and core logs but also information about coring intervals!


Then you create a dataset by specifying a path to a dir with your wells:
```python
well_ds = WellDataset(path=DATASET_PATH, dirs=True, sort=True)
```

And run a matching pipeline:
```python
matching_pipeline = (Pipeline()
    .check_regularity()
    .match_core_logs(mode="POROSITY ~ core_logs.POROSITY", save_report=True)
    .run(batch_size=1, n_epochs=1, shuffle=False, drop_last=False, bar=True, lazy=True)
)

(well_ds >> matching_pipeline).run()
```

As a result, each well directory will contain a file with optimal coring interval shifts.

**Comment by atwahsz** [comment]
What about units ? I see it’s done on inter CM or meters?? And I want feet
float

**Comment by alexandrkuvaev** [comment]
`PetroFlow` uses integer depths by design, since floating-point arithmetics significantly complicates the implementation of several preprocessing methods, such as cropping.

Currently `DEPTH` values in a `.las` file are assumed to be in meters and converted to centimeters automatically during data loading. Units are not parsed from a `.las` file header since they are optional and their format is not strictly fixed.

The easiest way to use feet-indexed data is to manually convert it to ints and store in a `.csv` file for each well. This workaround will make `PetroFlow` treat your depths as centimeters. Also make sure, that the logs step is constant after conversion.

**Comment by atwahsz** [comment]
Great work . I think an automated data setup would make this package
superior 👌 great work guys I’m loving it

**Comment by tkbw** [comment]
Hi 
I have two questions:
My first question is:
when you say :"...Note, that the matching procedure requires not only a pair of well and core logs but also information about coring intervals!"
I have the following for each well, is this enough to run the matching and shifting?.
1. logs.csv
2. boring_intervals.csv
3. core_logs.csv
4. meta.json

My second question is:
when I run the following, I get error:
well_ds = WellDataset(path="C:\ANACONDA\Petroflow\W7_4", dirs=True, sort=True)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-26-c6590c89e9b2> in <module>
----> 1 well_ds = WellDataset(path="C:\ANACONDA\Petroflow\W7_4", dirs=True, sort=True)

NameError: name 'WellDataset' is not defined

**Comment by alexandrkuvaev** [comment]
Hi!

> I have the following for each well, is this enough to run the matching and shifting?

Yep, that's enough

For the second question, please open a new issue with a small reproducible script included, probably you've just forgotten to import `PetroFlow`.

**Comment by yjhong89** [comment]
Hi!

I have questions about core-to-log matching.

Currently, I have well logs and core posority log for the same well. 

Is 'boring interval' file necessary  for matching?

And what is 'boring sequence/interval' exactly?

Thank you!
