### ISSUE TITLE
ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by tkbw** [gazprom-neft/petroflow#35]
when I run pip3 install git+https://github.com/gazprom-neft/petroflow.git

I get the following error messages:

 Stored in directory: C:\Users\tk\AppData\Local\Temp\pip-ephem-wheel-cache-uh8srw3g\wheels\51\b8\a4\c9bb0738248ac7154d35c52e73c79b6295faeed6733063d074
  Building wheel for blosc (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\progra~1\continuum\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tk\\AppData\\Local\\Temp\\pip-install-odctz9b4\\blosc\\setup.py'"'"'; __file__='"'"'C:\\Users\\tk\\AppData\\Local\\Temp\\pip-install-odctz9b4\\blosc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\tk\AppData\Local\Temp\pip-wheel-i0hz2uj0'
       cwd: C:\Users\tk\AppData\Local\Temp\pip-install-odctz9b4\blosc\
  Complete output (21 lines):
  SSE2 detected
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\blosc
  copying blosc\test.py -> build\lib.win-amd64-3.7\blosc
  copying blosc\toplevel.py -> build\lib.win-amd64-3.7\blosc
  copying blosc\version.py -> build\lib.win-amd64-3.7\blosc
  copying blosc\__init__.py -> build\lib.win-amd64-3.7\blosc
  running build_clib
  building 'lz4' library
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\c-blosc
  creating build\temp.win-amd64-3.7\c-blosc\internal-complibs
  creating build\temp.win-amd64-3.7\c-blosc\internal-complibs\lz4-1.8.3
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\-------10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcc-blosc/internal-complibs\lz4-1.8.3\lz4.c /Fobuild\temp.win-amd64-3.7\c-blosc/internal-complibs\lz4-1.8.3\lz4.obj
  lz4.c
  c:\users\tk\appdata\local\temp\pip-install-odctz9b4\blosc\c-blosc\internal-complibs\lz4-1.8.3\lz4.h(43): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for blosc
----------------------------------------------------------------------------------------------------------
  Running setup.py clean for blosc
Successfully built petroflow
Failed to build blosc
Installing collected packages: blosc, pyarrow, feather-format, tqdm, petroflow
    Running setup.py install for blosc ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\progra~1\continuum\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tk\\AppData\\Local\\Temp\\pip-install-odctz9b4\\blosc\\setup.py'"'"'; __file__='"'"'C:\\Users\\tk\\AppData\\Local\\Temp\\pip-install-odctz9b4\\blosc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tk\AppData\Local\Temp\pip-record-5t5emcdq\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\tk\AppData\Roaming\Python\Python37\Include\blosc'
         cwd: C:\Users\tk\AppData\Local\Temp\pip-install-odctz9b4\blosc\
    Complete output (21 lines):
    SSE2 detected
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\blosc
    copying blosc\test.py -> build\lib.win-amd64-3.7\blosc
    copying blosc\toplevel.py -> build\lib.win-amd64-3.7\blosc
    copying blosc\version.py -> build\lib.win-amd64-3.7\blosc
    copying blosc\__init__.py -> build\lib.win-amd64-3.7\blosc
    running build_clib
    building 'lz4' library
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\c-blosc
    creating build\temp.win-amd64-3.7\c-blosc\internal-complibs
    creating build\temp.win-amd64-3.7\c-blosc\internal-complibs\lz4-1.8.3
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcc-blosc/internal-complibs\lz4-1.8.3\lz4.c /Fobuild\temp.win-amd64-3.7\c-blosc/internal-complibs\lz4-1.8.3\lz4.obj
    lz4.c
    c:\users\tk\appdata\local\temp\pip-install-odctz9b4\blosc\c-blosc\internal-complibs\lz4-1.8.3\lz4.h(43): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\progra~1\continuum\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tk\\AppData\\Local\\Temp\\pip-install-odctz9b4\\blosc\\setup.py'"'"'; __file__='"'"'C:\\Users\\tk\\AppData\\Local\\Temp\\pip-install-odctz9b4\\blosc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tk\AppData\Local\Temp\pip-record-5t5emcdq\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\tk\AppData\Roaming\Python\Python37\Include\blosc' Check the logs for full command output.

(base) D:\ANACONDA>

**Comment by alexandrkuvaev** [comment]
Seems like `PyPI` doesn't contain a `wheel` for `blosc` package for your platform, so `pip` tries to compile it from source and fails because of your `Visual Studio` version.

I'd suggest doing the following:
- First, uninstall `PetroFlow` by running this command:
```bash
pip3 uninstall petroflow
```
- Then, since you use `conda`, install `blosc` manually:
```bash
conda install -c conda-forge python-blosc
```
- Finally, try reinstalling `PetroFlow` as usual:
```bash
pip3 install git+https://github.com/gazprom-neft/petroflow.git
```

**Comment by tkbw** [comment]
Hi
When I try to run pip3 uninstall petroflow, I get "WARNING: Skipping petroflow as it is not installed."
Then I run "conda install -c conda-forge python-blosc" this went fine.
When I run "pip3 install git+https://github.com/gazprom-neft/petroflow.git" I get the same error I had from before.

regards

**Comment by alexandrkuvaev** [comment]
Please check, that `pip3` points to the correct `pip` inside your `conda` environment by running `which pip3` and validating the returned path.

I've just run the installation process inside a clean `conda` env and it went perfectly fine.

**Comment by tkbw** [comment]
I have unistalled and installed again. I did which pip3 and I get "C:/PROGRA~1/Continuum/Anaconda3/Scripts/pip3.exe"
Then I tried to run,  conda install -c conda-forge python-blosc
(base) C:\>conda install -c conda-forge python-blosc
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\PROGRA~1\Continuum\Anaconda3

  added / updated specs:
    - python-blosc


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.5                |   py37hf50a25e_2         3.0 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.0 MB

The following packages will be UPDATED:

  conda                                4.8.5-py37hc8dfbb8_1 --> 4.8.5-py37hf50a25e_2


Proceed ([y]/n)? Y


Downloading and Extracting Packages
conda-4.8.5          | 3.0 MB    | ##################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: / WARNING conda.core.path_actions:verify(963): Unable to create environments file. Path not writable.
  environment location: C:\%HOMEDRIVE%%HOMEPATH%\.conda\environments.txt

done
Executing transaction: - WARNING conda.core.envs_manager:register_env(52): Unable to register environment. Path not writable or missing.
  environment location: C:\PROGRA~1\Continuum\Anaconda3
  registry file: C:\%HOMEDRIVE%%HOMEPATH%\.conda\environments.txt
done

------------------------------------------------
As you can see above Path not writable or missing.

**Comment by roman-kh** [comment]
Your conda installation seems broken as path `C:%HOMEDRIVE%%HOMEPATH%.conda\environments.txt` does not conform to Windows standards. It should look something like `%HOMEDRIVE%:\%HOMEPATH%\conda\environments.txt` and you need permissions to write to that file.

**Comment by tkbw** [comment]
how can I fix the path? I have uninstalled and installed again.

**Comment by TaqiRizvics** [comment]
I am getting the following error while installing opencv in windows can you help me with that 


Collecting opencv-python
  Using cached opencv-python-4.4.0.44.tar.gz (88.9 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\waleed computers\appdata\local\programs\python\python39\python.exe' 'c:\users\waleed computers\appdata\local\programs\python\python39\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Waleed Computers\AppData\Local\Temp\pip-build-env-_3b7kj_d\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake pip 'numpy==1.11.3; python_version=='"'"'3.5'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"''
       cwd: None
  Complete output (310 lines):
  Ignoring numpy: markers 'python_version == "3.5"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
  Collecting setuptools
    Using cached setuptools-50.3.1-py3-none-any.whl (785 kB)
  Collecting wheel
    Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
  Collecting scikit-build
    Using cached scikit_build-0.11.1-py2.py3-none-any.whl (72 kB)
  Collecting cmake
    Using cached cmake-3.18.2.post1-py3-none-win_amd64.whl (34.7 MB)
  Collecting pip
    Using cached pip-20.2.3-py2.py3-none-any.whl (1.5 MB)
  Collecting numpy==1.17.3
    Using cached numpy-1.17.3.zip (6.4 MB)
  Collecting packaging
    Using cached packaging-20.4-py2.py3-none-any.whl (37 kB)
  Collecting distro
    Using cached distro-1.5.0-py2.py3-none-any.whl (18 kB)
  Collecting six
    Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
  Collecting pyparsing>=2.0.2
    Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
  Using legacy 'setup.py install' for numpy, since package 'wheel' is not installed.
  Installing collected packages: setuptools, wheel, six, pyparsing, packaging, distro, scikit-build, cmake, pip, numpy
      Running setup.py install for numpy: started
      Running setup.py install for numpy: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\waleed computers\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Waleed Computers\\AppData\\Local\\Temp\\pip-install-y8e675oj\\numpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\Waleed Computers\\AppData\\Local\\Temp\\pip-install-y8e675oj\\numpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Waleed Computers\AppData\Local\Temp\pip-record-x0q0hnh_\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\Waleed Computers\AppData\Local\Temp\pip-build-env-_3b7kj_d\overlay' --compile --install-headers 'C:\Users\Waleed Computers\AppData\Local\Temp\pip-build-env-_3b7kj_d\overlay\Include\numpy'
           cwd: C:\Users\Waleed Computers\AppData\Local\Temp\pip-install-y8e675oj\numpy\
      Complete output (277 lines):
      Running from numpy source directory.

      Note: if you need reliable uninstall behavior, then install
      with pip instead of using `setup.py install`:

        - `pip install .`       (from a git repo or downloaded source
                                 release)
        - `pip install numpy`   (last NumPy release on PyPi)


      blas_opt_info:
      blas_mkl_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries mkl_rt not found in ['c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      blis_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries blis not found in ['c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      openblas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries openblas not found in ['c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\libs']
      get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      customize GnuFCompiler
      Could not locate executable g77
      Could not locate executable f77
      customize IntelVisualFCompiler
      Could not locate executable ifort
      Could not locate executable ifl
      customize AbsoftFCompiler
      Could not locate executable f90
      customize CompaqVisualFCompiler
      Could not locate executable DF
      customize IntelItaniumVisualFCompiler
      Could not locate executable efl
      customize Gnu95FCompiler
      Could not locate executable gfortran
      Could not locate executable f95
      customize G95FCompiler
      Could not locate executable g95
      customize IntelEM64VisualFCompiler
      customize IntelEM64TFCompiler
      Could not locate executable efort
      Could not locate executable efc
      customize PGroupFlangCompiler
      Could not locate executable flang
      don't know how to compile Fortran code on platform 'nt'
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas not found in ['c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      atlas_3_10_blas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas not found in ['c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in ['c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      atlas_blas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in ['c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      accelerate_info:
        NOT AVAILABLE

      C:\Users\Waleed Computers\AppData\Local\Temp\pip-install-y8e675oj\numpy\numpy\distutils\system_info.py:690: UserWarning:
          Optimized (vendor) Blas libraries are not found.
          Falls back to netlib Blas library which has worse performance.
          A better performance should be easily gained by switching
          Blas library.
        self.calc_info()
      blas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries blas not found in ['c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      C:\Users\Waleed Computers\AppData\Local\Temp\pip-install-y8e675oj\numpy\numpy\distutils\system_info.py:690: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        self.calc_info()
      blas_src_info:
        NOT AVAILABLE

      C:\Users\Waleed Computers\AppData\Local\Temp\pip-install-y8e675oj\numpy\numpy\distutils\system_info.py:690: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        self.calc_info()
        NOT AVAILABLE

      'svnversion' is not recognized as an internal or external command,
      operable program or batch file.
      non-existing path in 'numpy\\distutils': 'site.cfg'
      lapack_opt_info:
      lapack_mkl_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries mkl_rt not found in ['c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      openblas_lapack_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries openblas not found in ['c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      openblas_clapack_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries openblas,lapack not found in ['c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      flame_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries flame not found in ['c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas,tatlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas,tatlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries tatlas,tatlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\libs
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE

      atlas_3_10_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas,satlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas,satlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries satlas,satlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\libs
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE

      atlas_threads_info:
      Setting PTATLAS=ATLAS
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries ptf77blas,ptcblas,atlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\libs
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE

      atlas_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\lib
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in C:\
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack_atlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\libs
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries f77blas,cblas,atlas not found in c:\users\waleed computers\appdata\local\programs\python\python39\libs
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE

      lapack_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries lapack not found in ['c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\lib', 'C:\\', 'c:\\users\\waleed computers\\appdata\\local\\programs\\python\\python39\\libs']
        NOT AVAILABLE

      C:\Users\Waleed Computers\AppData\Local\Temp\pip-install-y8e675oj\numpy\numpy\distutils\system_info.py:1712: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
      lapack_src_info:
        NOT AVAILABLE

      C:\Users\Waleed Computers\AppData\Local\Temp\pip-install-y8e675oj\numpy\numpy\distutils\system_info.py:1712: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
        NOT AVAILABLE

      c:\users\waleed computers\appdata\local\programs\python\python39\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running install
      running build
      running config_cc
      unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      build_src
      building py_modules sources
      creating build
      creating build\src.win-amd64-3.9
      creating build\src.win-amd64-3.9\numpy
      creating build\src.win-amd64-3.9\numpy\distutils
      building library "npymath" sources
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
      ----------------------------------------
  ERROR: Command errored out with exit status 1: 'c:\users\waleed computers\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Waleed Computers\\AppData\\Local\\Temp\\pip-install-y8e675oj\\numpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\Waleed Computers\\AppData\\Local\\Temp\\pip-install-y8e675oj\\numpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Waleed Computers\AppData\Local\Temp\pip-record-x0q0hnh_\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\Waleed Computers\AppData\Local\Temp\pip-build-env-_3b7kj_d\overlay' --compile --install-headers 'C:\Users\Waleed Computers\AppData\Local\Temp\pip-build-env-_3b7kj_d\overlay\Include\numpy' Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\waleed computers\appdata\local\programs\python\python39\python.exe' 'c:\users\waleed computers\appdata\local\programs\python\python39\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Waleed Computers\AppData\Local\Temp\pip-build-env-_3b7kj_d\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake pip 'numpy==1.11.3; python_version=='"'"'3.5'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"'' Check the logs for full command output.

**Comment by roman-kh** [comment]
I would recommend to address this issue at opencv repo.
